--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/DeveloperNeb101/NoFallDamage
branches:
- master
projects:
  NoFallDamage:
  icon: "https://www.google.com/imgres?imgurl=https%3A%2F%2Fi.ytimg.com%2Fvi%2F2AHPrz2KKmA%2Fmaxresdefault.jpg&imgrefurl=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D2AHPrz2KKmA&docid=rY39hkot1aDOhM&tbnid=BeIyZ6OuEJiFsM%3A&vet=10ahUKEwigk4PFkNbeAhWFjVkKHYRwD_oQMwhDKAQwBA..i&w=1280&h=720&client=firefox-b-1-ab&bih=579&biw=1252&q=no%20fall%20damage&ved=0ahUKEwigk4PFkNbeAhWFjVkKHYRwD_oQMwhDKAQwBA&iact=mrc&uact=8"
    path: ""
...
