name: NoFallDamage
author: DeveloperNeb101
version: "1.0"
description: NoFallDamage Developed by DeveloperNeb101
api:
- 3.0.0

main: DeveloperNeb101\NoFallDamage\Main
commands: []
permissions: []